name: Vite.js CI and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify your Node.js version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the project
    - name: Build the project
      run: npm run build

    # Step 5: Verify build output
    - name: List build output
      run: ls -R ./dist

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: ./dist
      
    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        clean: true  # Ensures previous deployments are removed
